/**
 * ssd1322_test.c
 *
 * Test driver for NHD-2.8-25664 OLED display (SSD1322 controller)
 * Target: STM32 (HAL-based) via SPI
 *
 * Display specs:
 *   - Resolution: 256 x 64 pixels
 *   - Interface: 4-wire SPI
 *   - Grayscale: 16 levels (4-bit per pixel)
 *   - Each column address covers 4 pixels (2 bytes = 2 nibbles each)
 *
 * Wiring assumptions (adjust pin definitions below to match your board):
 *   STM32 SPI MOSI  -> Display SDIN
 *   STM32 SPI SCK   -> Display SCLK
 *   STM32 GPIO (CS) -> Display /CS  (active low)
 *   STM32 GPIO (DC) -> Display D/C# (low=command, high=data)
 *   STM32 GPIO (RST)-> Display /RES (active low)
 */

#include "main.h"       /* STM32 HAL header - adjust for your MCU family  */
#include <string.h>
#include <stdint.h>
#include "ssd1322.h"

#include "curlogo_240240.h"
//#include "testimage_240240.h"
//#include "curdisplay_240240.h"

#include "oled_display.h"
#include "curlogo_oled.h"


/* ─── Display geometry ─────────────────────────────────────────────────────── */

#define OLED_WIDTH          128
#define OLED_HEIGHT         64

/*
 * The SSD1322 maps two 4-bit grayscale pixels per byte.
 * Column addresses 0x1C–0x5B cover the visible 256-pixel range on this
 * module (each column address = 4 pixels wide → 64 column addresses × 4 = 256).
 */
#define OLED_COL_START      0x1C
#define OLED_COL_END        0x5B	// 0x5B
#define OLED_ROW_START      0x00
#define OLED_ROW_END        0x3F    /* 64 rows */

/* Frame buffer: 128 pixels wide × 64 rows, 4 bits per pixel → 64 bytes/row */
#define FB_STRIDE           (OLED_WIDTH)        /* 64 bytes per row      */
#define FB_SIZE             (FB_STRIDE * OLED_HEIGHT) /* 4096 bytes total     */

static uint8_t framebuf[FB_SIZE];

/* Forward-declare the SPI handle (generated by CubeMX) */
extern SPI_HandleTypeDef OLED_SPI_HANDLE;

/* ─── Low-level GPIO helpers ───────────────────────────────────────────────── */

inline void oled_cs_low(void)
{
    HAL_GPIO_WritePin(OLED_CS_PORT, OLED_CS_PIN, GPIO_PIN_RESET);
}

inline void oled_cs_high(void)
{
    HAL_GPIO_WritePin(OLED_CS_PORT, OLED_CS_PIN, GPIO_PIN_SET);
}

inline void oled_dc_command(void)
{
    HAL_GPIO_WritePin(OLED_DC_PORT, OLED_DC_PIN, GPIO_PIN_RESET);
}

inline void oled_dc_data(void)
{
    HAL_GPIO_WritePin(OLED_DC_PORT, OLED_DC_PIN, GPIO_PIN_SET);
}

/* ─── SPI transfer helpers ─────────────────────────────────────────────────── */

void oled_write_cmd(uint8_t cmd)
{
    oled_cs_low();
    oled_dc_command();
    HAL_SPI_Transmit(&OLED_SPI_HANDLE, &cmd, 1, HAL_SPI_DELAY);
    oled_cs_high();
}

void oled_write_data(uint8_t data)
{
    oled_cs_low();
    oled_dc_data();
    HAL_SPI_Transmit(&OLED_SPI_HANDLE, &data, 1, HAL_SPI_DELAY);
    oled_cs_high();
}

static void oled_write_data_buf(const uint8_t *buf, uint16_t len)
{
    oled_cs_low();
    oled_dc_data();
    HAL_SPI_Transmit(&OLED_SPI_HANDLE, (uint8_t *)buf, len, HAL_SPI_DELAY);
    oled_cs_high();
}

/**
 * Convert rgb888 to rgb565
 */
static uint16_t rgb888_to_rgb565(uint8_t r, uint8_t g, uint8_t b)
{
    return ((r >> 3) << 11) |   // 5 bits for red
           ((g >> 2) << 5)  |   // 6 bits for green
           (b >> 3);            // 5 bits for blue
}

/**
 * Read the ID
 */
static void oled_read_id(uint8_t * readBuffer)
{
	uint8_t buf = {0x04, 0x00, 0x00, 0x00};

	oled_cs_low();
	oled_dc_command();
	HAL_SPI_Transmit(&OLED_SPI_HANDLE, (uint8_t *)buf, 1, HAL_SPI_DELAY);
	oled_dc_data();
	HAL_SPI_Receive(&OLED_SPI_HANDLE, readBuffer, 4, HAL_SPI_DELAY);
	oled_cs_high();
}


/* ─── Hardware reset ───────────────────────────────────────────────────────── */

void oled_reset(void)
{
    HAL_GPIO_WritePin(OLED_RST_PORT, OLED_RST_PIN, GPIO_PIN_SET);
    HAL_Delay(100);
    HAL_GPIO_WritePin(OLED_RST_PORT, OLED_RST_PIN, GPIO_PIN_RESET);
    HAL_Delay(100);
    HAL_GPIO_WritePin(OLED_RST_PORT, OLED_RST_PIN, GPIO_PIN_SET);
    HAL_Delay(100);
}

/* ─── SSD1322 initialization sequence ─────────────────────────────────────── */

void oled_init(void)
{
    oled_reset();

    oled_write_cmd(0xFD);   /* Set command lock */
    oled_write_data(0x12);  /* Unlock */

    oled_write_cmd(0xAE);   /* Display OFF */

    oled_write_cmd(0xB3);   /* Set display clock divide ratio / oscillator freq */
    oled_write_data(0x91);  /* Divide ratio = 1, Fosc = ~85 Hz frame rate */

    oled_write_cmd(0xCA);   /* Set multiplex ratio */
    oled_write_data(0x3F);  /* 1/64 duty */

    oled_write_cmd(0xA2);   /* Set display offset */
    oled_write_data(0x00);	// 0x00

    oled_write_cmd(0xAB);   /* Function selection */
    oled_write_data(0x01);  /* Enable internal VDD regulator */

    oled_write_cmd(0xA0);   /* Set re-map / dual COM line mode */
    oled_write_data(0x16);  /* Column address remap ON, nibble remap ON */
    oled_write_data(0x11);  /* Dual COM mode enabled */

    oled_write_cmd(0xC7);   /* Master contrast current control */
    oled_write_data(0x0F);  /* Maximum */

    oled_write_cmd(0xC1);   /* Set contrast current */
    oled_write_data(0x9F);  /* 0x00–0xFF */

    oled_write_cmd(0xB1);   /* Set phase length */
    oled_write_data(0x72);  /* Phase 1 = 5, Phase 2 = 14 */  // F2

    oled_write_cmd(0xBB);   /* Set pre-charge voltage */
    oled_write_data(0x1F);

    oled_write_cmd(0xB4);   /* Set segment voltage reference */
    oled_write_data(0xA0);
    oled_write_data(0xFD);

    oled_write_cmd(0xBE);   /* Set VCOMH */
    oled_write_data(0x04);

    oled_write_cmd(0xA6);   /* Normal display mode (not inverted) */
    oled_write_cmd(0xAF);   /* Display ON */

    HAL_Delay(100);
}

/* ─── Frame buffer helpers ─────────────────────────────────────────────────── */

/**
 * Set a single pixel in the frame buffer.
 * @param x      Column 0..128
 * @param y      Row    0..63
 * @param gray   Grayscale value 0..15
 */
void oled_set_pixel(uint16_t x, uint16_t y, uint8_t gray)
{
    if (x >= OLED_WIDTH || y >= OLED_HEIGHT)
    	return;

	uint16_t index = (y * OLED_WIDTH) + x;

	framebuf[index] = gray;
	/*
	if (x & 1) {
		// odd pixel → low nibble
		framebuf[index] = (framebuf[index] & 0xF0) | (gray & 0x0F);
	} else {
		// even pixel → high nibble
		framebuf[index] = (framebuf[index] & 0x0F) | ((gray & 0x0F) << 4);
	}*/
}

/** Clear the frame buffer to a given grey level (0 = black, 15 = white). */
void oled_clear_fb(uint8_t gray)
{
    memset(framebuf, gray & 0x0F, FB_SIZE);
}

/**
 * Flush the entire frame buffer to the display.
 * Sends all 8192 bytes in a single DMA-friendly burst.
 */
void oled_flush(void)
{
    /* Set column address window */
    oled_write_cmd(0x15);
    oled_write_data(OLED_COL_START);
    oled_write_data(OLED_COL_END);

    /* Set row address window */
    oled_write_cmd(0x75);
    oled_write_data(OLED_ROW_START);
    oled_write_data(OLED_ROW_END);

    /* Begin RAM write */
    oled_write_cmd(0x5C);

    oled_write_data_buf(framebuf, FB_SIZE);
}

/* ─── Drawing primitives ───────────────────────────────────────────────────── */

/** Draw a horizontal line. */
void oled_hline(uint16_t x0, uint16_t x1, uint16_t y, uint8_t gray)
{
    if (x0 > x1) { uint16_t t = x0; x0 = x1; x1 = t; }
    for (uint16_t x = x0; x <= x1; x++) oled_set_pixel(x, y, gray);
}

/** Draw a vertical line. */
void oled_vline(uint16_t x, uint16_t y0, uint16_t y1, uint8_t gray)
{
    if (y0 > y1) { uint16_t t = y0; y0 = y1; y1 = t; }
    for (uint16_t y = y0; y <= y1; y++) oled_set_pixel(x, y, gray);
}

/** Draw a filled rectangle. */
void oled_fill_rect(uint16_t x, uint16_t y, uint16_t w, uint16_t h, uint8_t gray)
{
    for (uint16_t row = y; row < y + h && row < OLED_HEIGHT; row++)
        for (uint16_t col = x; col < x + w && col < OLED_WIDTH; col++)
            oled_set_pixel(col, row, gray);
}

/** Draw a rectangle outline. */
void oled_draw_rect(uint16_t x, uint16_t y, uint16_t w, uint16_t h, uint8_t gray)
{
    oled_hline(x, x + w - 1, y,         gray);
    oled_hline(x, x + w - 1, y + h - 1, gray);
    oled_vline(x,         y, y + h - 1, gray);
    oled_vline(x + w - 1, y, y + h - 1, gray);
}

/** Bresenham line drawing. */
void oled_draw_line(int16_t x0, int16_t y0, int16_t x1, int16_t y1, uint8_t gray)
{
    int16_t dx = (x1 > x0) ? (x1 - x0) : (x0 - x1);
    int16_t dy = (y1 > y0) ? (y1 - y0) : (y0 - y1);
    int16_t sx = (x0 < x1) ? 1 : -1;
    int16_t sy = (y0 < y1) ? 1 : -1;
    int16_t err = dx - dy;

    while (1) {
        oled_set_pixel((uint16_t)x0, (uint16_t)y0, gray);
        if (x0 == x1 && y0 == y1) break;
        int16_t e2 = 2 * err;
        if (e2 > -dy) { err -= dy; x0 += sx; }
        if (e2 <  dx) { err += dx; y0 += sy; }
    }
}

/* ─── Test patterns ────────────────────────────────────────────────────────── */

/**
 * Pattern 1: Full greyscale ramp
 * Divides the display into 16 vertical bands, one per grey level.
 */
static void test_greyscale_ramp(void)
{
    uint16_t band = OLED_WIDTH / 16;    /* 16 pixels per band */
    for (uint8_t g = 0; g < 16; g++)
        oled_fill_rect(g * band, 0, band, OLED_HEIGHT, g);
    oled_flush();
    HAL_Delay(2000);
}

/**
 * Pattern 2: Checkerboard
 * 8×8 pixel squares alternating between black (0) and white (15).
 */
static void test_checkerboard(void)
{
    oled_clear_fb(0);
    for (uint16_t y = 0; y < OLED_HEIGHT; y++)
    {
        for (uint16_t x = 0; x < OLED_WIDTH; x++)
        {
            if (((x / 8) + (y / 8)) & 1)
            	oled_set_pixel(x, y, 0xFF);
            else
            	oled_set_pixel(x, y, 0x00);
        }
    }
    oled_flush();
}

/**
 *
 */
static void test_image(uint8_t * pImg)
{
    oled_clear_fb(0);
    int i = 0;
    for (uint16_t y = 0; y < OLED_HEIGHT; y++)
    {
        for (uint16_t x = 0; x < OLED_WIDTH; x++)
        {
        	oled_set_pixel(x, y, pImg[i++]);
        }
    }
    oled_flush();
}

/**
 * Pattern 3: Border + crosshairs
 * Verifies correct pixel addressing at all four edges.
 */
static void test_border_crosshair(void)
{
    oled_clear_fb(0);
    oled_draw_rect(0, 0, OLED_WIDTH, OLED_HEIGHT, 15);
    oled_hline(0, OLED_WIDTH - 1, OLED_HEIGHT / 2, 8);
    oled_vline(OLED_WIDTH / 2, 0, OLED_HEIGHT - 1, 8);
    /* Corner marks */
    oled_fill_rect(0,              0,              4, 4, 15);
    oled_fill_rect(OLED_WIDTH - 4, 0,              4, 4, 15);
    oled_fill_rect(0,              OLED_HEIGHT - 4, 4, 4, 15);
    oled_fill_rect(OLED_WIDTH - 4, OLED_HEIGHT - 4, 4, 4, 15);
    oled_flush();
    HAL_Delay(2000);
}

/**
 * Pattern 4: Diagonal lines
 * Tests the Bresenham line draw routine.
 */
static void test_diagonal_lines(void)
{
    oled_clear_fb(0);
    oled_draw_line(0, 0, OLED_WIDTH - 1, OLED_HEIGHT - 1, 15);
    oled_draw_line(OLED_WIDTH - 1, 0, 0, OLED_HEIGHT - 1, 10);
    for (int i = 0; i < OLED_WIDTH; i += 32)
        oled_draw_line(i, 0, i + 32, OLED_HEIGHT - 1, 6);
    oled_flush();
    HAL_Delay(2000);
}

/**
 * Pattern 5: Horizontal scan (walking bright row)
 * Useful for checking row addressing and display uniformity.
 */
static void test_scan_rows(void)
{
    for (uint16_t y = 0; y < OLED_HEIGHT; y++) {
        oled_clear_fb(0);
        oled_hline(0, OLED_WIDTH - 1, y, 15);
        oled_flush();
        HAL_Delay(30);
    }
}

/**
 * Pattern 6: Pixel walk
 * Lights a single pixel and sweeps it left-to-right, top-to-bottom.
 * Very slow — useful as a deep sanity check, not for normal testing.
 * Uncomment the call in oled_run_tests() if needed.
 */
static void test_pixel_walk(void)
{
    for (uint16_t y = 0; y < OLED_HEIGHT; y++) {
        for (uint16_t x = 0; x < OLED_WIDTH; x++) {
            oled_clear_fb(0);
            oled_set_pixel(x, y, 15);
            oled_flush();
            HAL_Delay(5);
        }
    }
}

/* ─── Public test entry point ──────────────────────────────────────────────── */

/**
 * Call this once from main() after HAL and SPI peripherals are initialised.
 * Runs all test patterns in sequence, then loops the greyscale ramp.
 */
void oled_run_tests(void)
{
    oled_init();

    while (1)
    {
    	oled_clear_fb(0);
    	oled_flush();
    	HAL_Delay(1000);
    	test_checkerboard();
    	HAL_Delay(1000);

    	oled_write_cmd(0xA5);
    	HAL_Delay(1000);
    	oled_write_cmd(0xA6);
		HAL_Delay(1000);

		test_image(oled_display);
		HAL_Delay(3000);
		test_image(oled_logo);
		HAL_Delay(3000);

    }
}

/**
 *
 */
void tft_run_tests(void)
{
	HAL_GPIO_WritePin(OLED_RST_PORT, OLED_RST_PIN, GPIO_PIN_SET);
	HAL_Delay(10);
	HAL_GPIO_WritePin(OLED_RST_PORT, OLED_RST_PIN, GPIO_PIN_RESET);
	HAL_Delay(250);
	HAL_GPIO_WritePin(OLED_RST_PORT, OLED_RST_PIN, GPIO_PIN_SET);
	HAL_Delay(250);

	oled_write_cmd(0x01);
	HAL_Delay(120);

	oled_write_cmd(0x28);	// display off
	oled_write_cmd(0x11);	// exit sleep mode
	HAL_Delay(200);

	oled_write_cmd(0x36);
	oled_write_data(0x00);  // MADCTL

	oled_write_cmd(0x3A);
	oled_write_data(0x55);   //COLMOD: Interface Pixel format RGB565
	  oled_write_cmd(0x2A);
	  oled_write_data(0x00);
	  oled_write_data(0x00);
	  oled_write_data(0x00);
	  oled_write_data(0xEF); //X address set

	  oled_write_cmd(0x2B);
	  oled_write_data(0x00);
	  oled_write_data(0x00);
	  oled_write_data(0x00);
	  oled_write_data(0xEF); //Y address set

	  HAL_Delay(10);

	  oled_write_cmd(0x21);
	  oled_write_cmd(0x29);
	  HAL_Delay(10);



	  while (1)
	  {
		  uint8_t cmd = 0x2C;
		  uint8_t dat = 0xAA;

		  // Display Logo
		  uint8_t pixel[2] = {0x00, 0x00};
		  uint8_t rgbTemp[3] = {0};
		  uint8_t * pData = (uint8_t *)header_data;

		  oled_cs_low();
		  oled_dc_command();
		  HAL_SPI_Transmit(&OLED_SPI_HANDLE, &cmd, 1, HAL_SPI_DELAY);
		  oled_dc_data();
		  for (int i = 0; i < (240*240); i++)
		  {
			  // Grab pixel data
			  HEADER_PIXEL(pData, rgbTemp);

			  // Convert to 565 and store
			  uint16_t rgb565Pixel = rgb888_to_rgb565(rgbTemp[2], rgbTemp[0], rgbTemp[1]);

			  pixel[0] = rgb565Pixel & 0xFF;
			  pixel[1] = rgb565Pixel >> 8;
			  HAL_SPI_Transmit(&OLED_SPI_HANDLE, &pixel, 2, HAL_SPI_DELAY);
		  }
		  oled_cs_high();

		  HAL_Delay(3000);


		  // Display demo gui with numbers and symbols


		  HAL_Delay(3000);

	  }
}

/* ─── End of file ──────────────────────────────────────────────────────────── */
